// filters.js

const filters = [
  {
    id: "employee",
    name: "Employee",
    options: [
      { value: "1-10", label: "1-10" },
      { value: "11-50", label: "11-50" },
      { value: "51-200", label: "51-200" },
      { value: "201-500", label: "201-500" },
      { value: "501-1,000", label: "501-1,000" },
      { value: "1,001-5,000", label: "1,001-5,000" },
      { value: "5,001-10,000", label: "5,001-10,000" },
      { value: "10,001+", label: "10,001+" },
    ],
  },
  {
    id: "industry",
    name: "Industry",
    options: [
      {
        value: "Advertising/Media/Publishing",
        label: "Advertising/Media/Publishing",
      },
      { value: "Aerospace and Aviation", label: "Aerospace and Aviation" },
      { value: "Agriculture and Forestry", label: "Agriculture and Forestry" },
      {
        value: "Banking/Accounting/Financial",
        label: "Banking/Accounting/Financial",
      },
      { value: "Business Services", label: "Business Services" },
      { value: "Computer and Technology", label: "Computer and Technology" },
      { value: "Education", label: "Education" },
      {
        value: "Engineering and Construction",
        label: "Engineering and Construction",
      },
      {
        value: "Entertainment/Travel/Hospitality",
        label: "Entertainment/Travel/Hospitality",
      },
      { value: "Food and Beverage", label: "Food and Beverage" },
      { value: "Government", label: "Government" },
      { value: "Healthcare", label: "Healthcare" },
      { value: "Legal Solutions", label: "Legal Solutions" },
      { value: "Manufacturing", label: "Manufacturing" },
      { value: "Non profit Organizations", label: "Non profit Organizations" },
      { value: "Oil, Gas and Mining", label: "Oil, Gas and Mining" },
      { value: "Other", label: "Other" },
      { value: "Professional services", label: "Professional services" },
      { value: "Public Relations", label: "Public Relations" },
      { value: "Real Estate", label: "Real Estate" },
      { value: "Renewables & Environment", label: "Renewables & Environment" },
      { value: "Research", label: "Research" },
      { value: "Retail", label: "Retail" },
      { value: "Telecommunications", label: "Telecommunications" },
      {
        value: "Transportation and Shipping",
        label: "Transportation and Shipping",
      },
      { value: "Utilities", label: "Utilities" },
      { value: "Wholesale", label: "Wholesale" },
    ],
  },
  {
    id: "title",
    name: "Job Title",
    options: [],
  },
  {
    id: "Lead Tagging",
    name: "Lead Tagging",
    options: [
      { value: "Hot lead L1", label: "Hot lead L1" },
      { value: "Hot lead L2", label: "Hot lead L2" },
      { value: "Verified", label: "Verified" },
    ],
  },
  {
    id: "region",
    name: "Region",
    options: [
      { value: "Africa", label: "Africa" },
      { value: "Asia", label: "Asia" },
      { value: "Benelux", label: "Benelux" },
      { value: "DACH", label: "DACH" },
      { value: "Europe", label: "Europe" },
      { value: "MENA", label: "MENA" },
      { value: "Nordics", label: "Nordics" },
      { value: "North America", label: "North America" },
      { value: "Oceania", label: "Oceania" },
      { value: "South America", label: "South America" },
    ],
  },
  {
    id: "country",
    name: "Country",
    options: [
      { value: "Afghanistan", label: "Afghanistan" },
      { value: "Albania", label: "Albania" },
      { value: "Algeria", label: "Algeria" },
      { value: "Andorra", label: "Andorra" },
      { value: "Angola", label: "Angola" },
      { value: "Argentina", label: "Argentina" },
      { value: "Armenia", label: "Armenia" },
      { value: "Australia", label: "Australia" },
      { value: "Austria", label: "Austria" },
      { value: "Azerbaijan", label: "Azerbaijan" },
      { value: "Bahrain", label: "Bahrain" },
      { value: "Bangladesh", label: "Bangladesh" },
      { value: "Belarus", label: "Belarus" },
      { value: "Belgium", label: "Belgium" },
      { value: "Bolivia", label: "Bolivia" },
      { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
      { value: "Botswana", label: "Botswana" },
      { value: "Brazil", label: "Brazil" },
      {
        value: "British Indian Ocean Territory",
        label: "British Indian Ocean Territory",
      },
      { value: "British Virgin Islands", label: "British Virgin Islands" },
      { value: "Brunei", label: "Brunei" },
      { value: "Bulgaria", label: "Bulgaria" },
      { value: "Cambodia", label: "Cambodia" },
      { value: "Cameroon", label: "Cameroon" },
      { value: "Canada", label: "Canada" },
      { value: "Cayman Islands", label: "Cayman Islands" },
      { value: "Chile", label: "Chile" },
      { value: "China", label: "China" },
      { value: "Colombia", label: "Colombia" },
      { value: "Costa Rica", label: "Costa Rica" },
      { value: "Cote Dlvoire", label: "Cote Dlvoire" },
      { value: "Croatia", label: "Croatia" },
      { value: "Cyprus", label: "Cyprus" },
      { value: "Czechia", label: "Czechia" },
      { value: "Denmark", label: "Denmark" },
      { value: "Dominican Republic", label: "Dominican Republic" },
      { value: "Ecuador", label: "Ecuador" },
      { value: "Egypt", label: "Egypt" },
      { value: "El Salvador", label: "El Salvador" },
      { value: "Estonia", label: "Estonia" },
      { value: "Ethiopia", label: "Ethiopia" },
      { value: "Fiji", label: "Fiji" },
      { value: "Finland", label: "Finland" },
      { value: "France", label: "France" },
      { value: "French Polynesia", label: "French Polynesia" },
      { value: "Georgia", label: "Georgia" },
      { value: "Germany", label: "Germany" },
      { value: "Ghana", label: "Ghana" },
      { value: "Greece", label: "Greece" },
      { value: "Guatemala", label: "Guatemala" },
      { value: "Honduras", label: "Honduras" },
      { value: "Hong Kong", label: "Hong Kong" },
      { value: "Hungary", label: "Hungary" },
      { value: "Iceland", label: "Iceland" },
      { value: "India", label: "India" },
      { value: "Indonesia", label: "Indonesia" },
      { value: "Iran", label: "Iran" },
      { value: "Iraq", label: "Iraq" },
      { value: "Ireland", label: "Ireland" },
      { value: "Israel", label: "Israel" },
      { value: "Italy", label: "Italy" },
      { value: "Ivory Coast", label: "Ivory Coast" },
      { value: "Jamaica", label: "Jamaica" },
      { value: "Japan", label: "Japan" },
      { value: "Jordan", label: "Jordan" },
      { value: "Kazakhstan", label: "Kazakhstan" },
      { value: "Kenya", label: "Kenya" },
      { value: "Kuwait", label: "Kuwait" },
      { value: "Laos", label: "Laos" },
      { value: "Latvia", label: "Latvia" },
      { value: "Lebanon", label: "Lebanon" },
      { value: "Libya", label: "Libya" },
      { value: "Liechtenstein", label: "Liechtenstein" },
      { value: "Lithuania", label: "Lithuania" },
      { value: "Luxembourg", label: "Luxembourg" },
      { value: "Macau", label: "Macau" },
      { value: "Malaysia", label: "Malaysia" },
      { value: "Malta", label: "Malta" },
      { value: "Mauritius", label: "Mauritius" },
      { value: "Mexico", label: "Mexico" },
      { value: "Monaco", label: "Monaco" },
      { value: "Morocco", label: "Morocco" },
      { value: "Myanmar", label: "Myanmar" },
      { value: "Namibia", label: "Namibia" },
      { value: "Nepal", label: "Nepal" },
      { value: "Netherlands", label: "Netherlands" },
      { value: "New Zealand", label: "New Zealand" },
      { value: "Nicaragua", label: "Nicaragua" },
      { value: "Nigeria", label: "Nigeria" },
      { value: "North Korea", label: "North Korea" },
      { value: "North Macedonia", label: "North Macedonia" },
      { value: "Norway", label: "Norway" },
      { value: "Oman", label: "Oman" },
      { value: "Pakistan", label: "Pakistan" },
      { value: "Panama", label: "Panama" },
      { value: "Papua New Guinea", label: "Papua New Guinea" },
      { value: "Paraguay", label: "Paraguay" },
      { value: "Peru", label: "Peru" },
      { value: "Philippines", label: "Philippines" },
      { value: "Poland", label: "Poland" },
      { value: "Portugal", label: "Portugal" },
      { value: "Puerto Rico", label: "Puerto Rico" },
      { value: "Qatar", label: "Qatar" },
      { value: "Romania", label: "Romania" },
      { value: "Russia", label: "Russia" },
      { value: "Rwanda", label: "Rwanda" },
      { value: "Saudi Arabia", label: "Saudi Arabia" },
      { value: "Senegal", label: "Senegal" },
      { value: "Serbia", label: "Serbia" },
      { value: "Seychelles", label: "Seychelles" },
      { value: "Singapore", label: "Singapore" },
      { value: "Slovakia", label: "Slovakia" },
      { value: "Slovenia", label: "Slovenia" },
      { value: "South Africa", label: "South Africa" },
      { value: "South Korea", label: "South Korea" },
      { value: "Spain", label: "Spain" },
      { value: "Sri Lanka", label: "Sri Lanka" },
      { value: "Sudan", label: "Sudan" },
      { value: "Sweden", label: "Sweden" },
      { value: "Switzerland", label: "Switzerland" },
      { value: "Syria", label: "Syria" },
      { value: "Taiwan", label: "Taiwan" },
      { value: "Tanzania", label: "Tanzania" },
      { value: "Thailand", label: "Thailand" },
      { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
      { value: "Tunisia", label: "Tunisia" },
      { value: "Turkey", label: "Turkey" },
      { value: "Turkmenistan", label: "Turkmenistan" },
      { value: "Uganda", label: "Uganda" },
      { value: "Ukraine", label: "Ukraine" },
      { value: "United Arab Emirates", label: "United Arab Emirates" },
      { value: "United Kingdom", label: "United Kingdom" },
      { value: "United States", label: "United States" },
      { value: "Uruguay", label: "Uruguay" },
      { value: "Venezuela", label: "Venezuela" },
      { value: "Vietnam", label: "Vietnam" },
      { value: "Yemen", label: "Yemen" },
      { value: "Zambia", label: "Zambia" },
      { value: "Zimbabwe", label: "Zimbabwe" },
    ],
  },
  {
    id: "state",
    name: "State",
    options: [
      // States could be dynamically loaded based on the selected country
      { value: "California", label: "California" },
      { value: "New York", label: "New York" },
      // Add more states as needed
    ],
  },
  {
    id: "city",
    name: "City",
    options: [
      // Cities could be dynamically loaded based on the selected state
      { value: "Los Angeles", label: "Los Angeles" },
      { value: "New York City", label: "New York City" },
      // Add more cities as needed
    ],
  },
  {
    id: "sub_industry",
    name: "sub_industry",
    options: [
{ value:"Accounting", label:"Accounting" },
{ value:"Advertising Services", label:"Advertising Services" },
{ value:"Aerospace and Aviation", label:"Aerospace and Aviation" },
{ value:"Agriculture", label:"Agriculture" },
{ value:"Airlines and Aviation", label:"Airlines and Aviation" },
{ value:"Alternative Dispute Resolution", label:"Alternative Dispute Resolution" },
{ value:"Alternative Medicine", label:"Alternative Medicine" },
{ value:"Ambulance Services", label:"Ambulance Services" },
{ value:"Amusement Parks, Arcades & Attractions", label:"Amusement Parks, Arcades & Attractions" },
{ value:"Animation and Post-production", label:"Animation and Post-production" },
{ value:"Apparel & Fashion", label:"Apparel & Fashion" },
{ value:"Appliances", label:"Appliances" },
{ value:"Auctions, Retail", label:"Auctions, Retail" },
{ value:"Automation Machinery Manufacturing", label:"Automation Machinery Manufacturing" },
{ value:"Banking", label:"Banking" },
{ value:"Blood & Organ Banks", label:"Blood & Organ Banks" },
{ value:"Boats & Submarines", label:"Boats & Submarines" },
{ value:"Book and Periodical Publishing", label:"Book and Periodical Publishing" },
{ value:"Broadcast Media Production and Distribution", label:"Broadcast Media Production and Distribution" },
{ value:"Building Materials", label:"Building Materials" },
{ value:"Business Consulting and Services", label:"Business Consulting and Services" },
{ value:"Business Intelligence", label:"Business Intelligence" },
{ value:"Business Services", label:"Business Services" },
{ value:"Business Supplies & Equipment", label:"Business Supplies & Equipment" },
{ value:"Cable and Satellite Programming", label:"Cable and Satellite Programming" },
{ value:"Call Centers & Business Centers", label:"Call Centers & Business Centers" },
{ value:"Capital Markets", label:"Capital Markets" },
{ value:"Chambers of Commerce", label:"Chambers of Commerce" },
{ value:"Chemical Manufacturing", label:"Chemical Manufacturing" },
{ value:"Chemicals & Related Products", label:"Chemicals & Related Products" },
{ value:"Civic and Social Organizations", label:"Civic and Social Organizations" },
{ value:"Civil Engineering", label:"Civil Engineering" },
{ value:"Cleaning Products", label:"Cleaning Products" },
{ value:"Colleges & Universities", label:"Colleges & Universities" },
{ value:"Commercial and Industrial Machinery Maintenance", label:"Commercial and Industrial Machinery Maintenance" },
{ value:"Commercial Printing", label:"Commercial Printing" },
{ value:"Computer and Network Security", label:"Computer and Network Security" },
{ value:"Computer Equipment & Peripherals", label:"Computer Equipment & Peripherals" },
{ value:"Computer Games", label:"Computer Games" },
{ value:"Computer Hardware Manufacturing", label:"Computer Hardware Manufacturing" },
{ value:"Computer Networking Products", label:"Computer Networking Products" },
{ value:"Computer Software", label:"Computer Software" },
{ value:"Construction", label:"Construction" },
{ value:"Consumer Goods ", label:"Consumer Goods " },
{ value:"Consumer Services", label:"Consumer Services" },
{ value:"Content & Collaboration Software", label:"Content & Collaboration Software" },
{ value:"Convenience Stores", label:"Convenience Stores" },
{ value:"Cosmetics", label:"Cosmetics" },
{ value:"Courts of Law", label:"Courts of Law" },
{ value:"Credit Cards & Transaction Processing", label:"Credit Cards & Transaction Processing" },
{ value:"Crowdsourcing", label:"Crowdsourcing" },
{ value:"Cultural & Informational Centers", label:"Cultural & Informational Centers" },
{ value:"Custom Software & IT Services", label:"Custom Software & IT Services" },
{ value:"Customer Relationship Management (CRM) Software", label:"Customer Relationship Management (CRM) Software" },
{ value:"Dairy Product Manufacturing", label:"Dairy Product Manufacturing" },
{ value:"Data Collection & Internet Portals", label:"Data Collection & Internet Portals" },
{ value:"Data Security Software Products", label:"Data Security Software Products" },
{ value:"Database & File Management Software", label:"Database & File Management Software" },
{ value:"Debt Collection", label:"Debt Collection" },
{ value:"Defense and Space Manufacturing", label:"Defense and Space Manufacturing" },
{ value:"Dental Offices", label:"Dental Offices" },
{ value:"Department Stores", label:"Department Stores" },
{ value:"Design Services", label:"Design Services" },
{ value:"Drug Stores & Pharmacies", label:"Drug Stores & Pharmacies" },
{ value:"E-Commerce", label:"E-Commerce" },
{ value:"E-Learning Providers", label:"E-Learning Providers" },
{ value:"Education Administration Programs", label:"Education Administration Programs" },
{ value:"Elderly Care Services", label:"Elderly Care Services" },
{ value:"Electrical & Electronic Manufacturing", label:"Electrical & Electronic Manufacturing" },
{ value:"Electrical Equipment Manufacturing", label:"Electrical Equipment Manufacturing" },
{ value:"Electronics", label:"Electronics" },
{ value:"Engineering Services", label:"Engineering Services" },
{ value:"Engineering Software", label:"Engineering Software" },
{ value:"Enterprise Resource Planning (ERP) Software", label:"Enterprise Resource Planning (ERP) Software" },
{ value:"Entertainment Providers", label:"Entertainment Providers" },
{ value:"Environmental Services", label:"Environmental Services" },
{ value:"Events Services", label:"Events Services" },
{ value:"Executive Offices", label:"Executive Offices" },
{ value:"Facilities Management & Commercial Cleaning", label:"Facilities Management & Commercial Cleaning" },
{ value:"Facilities Services", label:"Facilities Services" },
{ value:"Farming, Ranching, Forestry", label:"Farming, Ranching, Forestry" },
{ value:"Federal", label:"Federal" },
{ value:"Financial Services", label:"Financial Services" },
{ value:"Financial Software", label:"Financial Software" },
{ value:"Fine Arts Schools", label:"Fine Arts Schools" },
{ value:"Fisheries", label:"Fisheries" },
{ value:"Fitness & Dance Facilities", label:"Fitness & Dance Facilities" },
{ value:"Flowers", label:"Flowers" },
{ value:"Food & Beverages", label:"Food & Beverages" },
{ value:"Food Service", label:"Food Service" },
{ value:"Freight & Logistics Services", label:"Freight & Logistics Services" },
{ value:"Fundraising", label:"Fundraising" },
{ value:"Furniture, Retail", label:"Furniture, Retail" },
{ value:"Gambling & Gaming", label:"Gambling & Gaming" },
{ value:"Glass & Clay", label:"Glass & Clay" },
{ value:"Glass, Ceramics and Concrete Manufacturing", label:"Glass, Ceramics and Concrete Manufacturing" },
{ value:"Government Administration", label:"Government Administration" },
{ value:"Grant Development Services", label:"Grant Development Services" },
{ value:"Graphic Design", label:"Graphic Design" },
{ value:"Grocery Retail", label:"Grocery Retail" },
{ value:"Hand", label:"Hand" },
{ value:"Health", label:"Health" },
{ value:"Health & Nutrition Products", label:"Health & Nutrition Products" },
{ value:"Healthcare Services", label:"Healthcare Services" },
{ value:"Healthcare Software", label:"Healthcare Software" },
{ value:"Higher Education", label:"Higher Education" },
{ value:"Holding Companies & Conglomerates", label:"Holding Companies & Conglomerates" },
{ value:"Home Improvement & Hardware Retail", label:"Home Improvement & Hardware Retail" },
{ value:"Hospital & Health Care", label:"Hospital & Health Care" },
{ value:"Hospitality", label:"Hospitality" },
{ value:"Hospitals & Physicians Clinics", label:"Hospitals & Physicians Clinics" },
{ value:"Hospitals and Health Care", label:"Hospitals and Health Care" },
{ value:"Household and Institutional Furniture Manufacturing", label:"Household and Institutional Furniture Manufacturing" },
{ value:"Household Goods", label:"Household Goods" },
{ value:"Human Resources Services", label:"Human Resources Services" },
{ value:"Human Resources Software", label:"Human Resources Software" },
{ value:"Individual & Family Services", label:"Individual & Family Services" },
{ value:"Individual and Family Services", label:"Individual and Family Services" },
{ value:"Industrial Automation", label:"Industrial Automation" },
{ value:"Industrial Machinery & Equipment", label:"Industrial Machinery & Equipment" },
{ value:"Information & Document Management", label:"Information & Document Management" },
{ value:"Information Technology", label:"Information Technology" },
{ value:"Insurance", label:"Insurance" },
{ value:"Interior design and home décor", label:"Interior design and home décor" },
{ value:"International Affairs", label:"International Affairs" },
{ value:"international trade and development", label:"international trade and development" },
{ value:"Internet Publishing", label:"Internet Publishing" },
{ value:"Internet Service Providers", label:"Internet Service Providers" },
{ value:"Investment", label:"Investment" },
{ value:"Investment Management", label:"Investment Management" },
{ value:"IT Infrastructure", label:"IT Infrastructure" },
{ value:"IT Services and IT Consulting", label:"IT Services and IT Consulting" },
{ value:"K-12 Schools", label:"K-12 Schools" },
{ value:"Law Enforcement", label:"Law Enforcement" },
{ value:"Law Practice", label:"Law Practice" },
{ value:"Legal Services", label:"Legal Services" },
{ value:"Legislative Offices", label:"Legislative Offices" },
{ value:"Lending & Brokerage", label:"Lending & Brokerage" },
{ value:"Libraries", label:"Libraries" },
{ value:"Local", label:"Local" },
{ value:"Lodging & Resorts", label:"Lodging & Resorts" },
{ value:"Logistics & Supply Chain", label:"Logistics & Supply Chain" },
{ value:"Machinery Manufacturing", label:"Machinery Manufacturing" },
{ value:"Management Consulting", label:"Management Consulting" },
{ value:"Manufacturing", label:"Manufacturing" },
{ value:"Marine Shipping & Transportation", label:"Marine Shipping & Transportation" },
{ value:"Maritime Transportation", label:"Maritime Transportation" },
{ value:"Market Research", label:"Market Research" },
{ value:"Marketing & Advertising", label:"Marketing & Advertising" },
{ value:"Marketing Services", label:"Marketing Services" },
{ value:"Mechanical Or Industrial Engineering", label:"Mechanical Or Industrial Engineering" },
{ value:"Media & Internet", label:"Media & Internet" },
{ value:"Media Production", label:"Media Production" },
{ value:"Medical & Surgical Hospitals", label:"Medical & Surgical Hospitals" },
{ value:"Medical Devices", label:"Medical Devices" },
{ value:"Medical Equipment Manufacturing", label:"Medical Equipment Manufacturing" },
{ value:"Medical Laboratories & Imaging Centers", label:"Medical Laboratories & Imaging Centers" },
{ value:"Medical Practices", label:"Medical Practices" },
{ value:"Medical Specialists", label:"Medical Specialists" },
{ value:"Mental Health & Rehabilitation Facilities", label:"Mental Health & Rehabilitation Facilities" },
{ value:"Mental Health Care", label:"Mental Health Care" },
{ value:"Metal Ore Mining", label:"Metal Ore Mining" },
{ value:"Military and International Affairs", label:"Military and International Affairs" },
{ value:"Minerals & Mining", label:"Minerals & Mining" },
{ value:"Mining & Metals", label:"Mining & Metals" },
{ value:"Mobile App Development", label:"Mobile App Development" },
{ value:"Mobile Computing Software Products", label:"Mobile Computing Software Products" },
{ value:"Mobile Gaming Apps", label:"Mobile Gaming Apps" },
{ value:"Motion Pictures & Film", label:"Motion Pictures & Film" },
{ value:"Motor Vehicle Manufacturing", label:"Motor Vehicle Manufacturing" },
{ value:"Motor Vehicles", label:"Motor Vehicles" },
{ value:"Movie Theaters", label:"Movie Theaters" },
{ value:"Movies, Videos, and Sound", label:"Movies, Videos, and Sound" },
{ value:"Multimedia", label:"Multimedia" },
{ value:"Multimedia & Graphic Design", label:"Multimedia & Graphic Design" },
{ value:"Museums & Art Galleries", label:"Museums & Art Galleries" },
{ value:"Museums, Historical Sites, and Zoos", label:"Museums, Historical Sites, and Zoos" },
{ value:"Music Production & Services", label:"Music Production & Services" },
{ value:"Musicians", label:"Musicians" },
{ value:"Networking Software", label:"Networking Software" },
{ value:"Newspaper Publishing", label:"Newspaper Publishing" },
{ value:"Newspapers & News Services", label:"Newspapers & News Services" },
{ value:"Non profit Organizations", label:"Non profit Organizations" },
{ value:"Office Products Retail & Distribution", label:"Office Products Retail & Distribution" },
{ value:"Oil and Gas", label:"Oil and Gas" },
{ value:"Online Audio and Video Media", label:"Online Audio and Video Media" },
{ value:"Online Media", label:"Online Media" },
{ value:"Others", label:"Others" },
{ value:"Outsourcing and Offshoring Consulting", label:"Outsourcing and Offshoring Consulting" },
{ value:"Outsourcing/Offshoring", label:"Outsourcing/Offshoring" },
{ value:"Package/Freight Delivery", label:"Package/Freight Delivery" },
{ value:"Packaging & Containers", label:"Packaging & Containers" },
{ value:"Paper & Forest Products", label:"Paper & Forest Products" },
{ value:"Paper and Forest Product Manufacturing", label:"Paper and Forest Product Manufacturing" },
{ value:"Performing Arts", label:"Performing Arts" },
{ value:"Performing Arts and Spectator Sports", label:"Performing Arts and Spectator Sports" },
{ value:"Performing Arts Theaters", label:"Performing Arts Theaters" },
{ value:"Periodical Publishing", label:"Periodical Publishing" },
{ value:"Pet Products", label:"Pet Products" },
{ value:"Pharmaceutical Manufacturing", label:"Pharmaceutical Manufacturing" },
{ value:"Pharmaceuticals", label:"Pharmaceuticals" },
{ value:"Philanthropic Fundraising Services", label:"Philanthropic Fundraising Services" },
{ value:"Photographic & Optical Equipment", label:"Photographic & Optical Equipment" },
{ value:"Photography", label:"Photography" },
{ value:"Physicians Clinics", label:"Physicians Clinics" },
{ value:"Plastic", label:"Plastic" },
{ value:"Plastics Manufacturing", label:"Plastics Manufacturing" },
{ value:"Political Organizations", label:"Political Organizations" },
{ value:"Primary and Secondary Education", label:"Primary and Secondary Education" },
{ value:"Primary/Secondary Education", label:"Primary/Secondary Education" },
{ value:"Printing Services", label:"Printing Services" },
{ value:"Professional Training & Coaching", label:"Professional Training & Coaching" },
{ value:"Public Policy Offices", label:"Public Policy Offices" },
{ value:"Public Relations and Communications Services", label:"Public Relations and Communications Services" },
{ value:"Public Safety", label:"Public Safety" },
{ value:"Publishing", label:"Publishing" },
{ value:"Pulp & Paper", label:"Pulp & Paper" },
{ value:"Radio and Television Broadcasting", label:"Radio and Television Broadcasting" },
{ value:"Rail", label:"Rail" },
{ value:"Railroad Equipment Manufacturing", label:"Railroad Equipment Manufacturing" },
{ value:"Ranching", label:"Ranching" },
{ value:"Real Estate", label:"Real Estate" },
{ value:"Record", label:"Record" },
{ value:"Recreational Facilities & Services", label:"Recreational Facilities & Services" },
{ value:"Religious Institutions", label:"Religious Institutions" },
{ value:"Renewables & Environment", label:"Renewables & Environment" },
{ value:"Research", label:"Research" },
{ value:"Research & Development", label:"Research & Development" },
{ value:"Research Services", label:"Research Services" },
{ value:"Restaurants", label:"Restaurants" },
{ value:"Retail", label:"Retail" },
{ value:"Retail Groceries", label:"Retail Groceries" },
{ value:"Retail Luxury Goods and Jewelry", label:"Retail Luxury Goods and Jewelry" },
{ value:"Search Engine", label:"Search Engine" },
{ value:"security and investigations", label:"security and investigations" },
{ value:"Security Products & Services", label:"Security Products & Services" },
{ value:"Security Software", label:"Security Software" },
{ value:"Semiconductor Manufacturing", label:"Semiconductor Manufacturing" },
{ value:"Semiconductors", label:"Semiconductors" },
{ value:"Shipbuilding", label:"Shipbuilding" },
{ value:"Social Media", label:"Social Media" },
{ value:"Social Networks", label:"Social Networks" },
{ value:"Software Development", label:"Software Development" },
{ value:"Sporting & Recreational Equipment Retail", label:"Sporting & Recreational Equipment Retail" },
{ value:"Sporting Goods", label:"Sporting Goods" },
{ value:"Sporting Goods Manufacturing", label:"Sporting Goods Manufacturing" },
{ value:"Sports and Recreation Instruction", label:"Sports and Recreation Instruction" },
{ value:"Sports Teams & Leagues", label:"Sports Teams & Leagues" },
{ value:"Staffing and Recruiting", label:"Staffing and Recruiting" },
{ value:"State, Government", label:"State, Government" },
{ value:"Storage & System Management Software", label:"Storage & System Management Software" },
{ value:"Strategic Management Services", label:"Strategic Management Services" },
{ value:"Supply Chain Management (SCM) Software", label:"Supply Chain Management (SCM) Software" },
{ value:"Telecommunication Equipment", label:"Telecommunication Equipment" },
{ value:"Telecommunications", label:"Telecommunications" },
{ value:"Telephony & Wireless", label:"Telephony & Wireless" },
{ value:"Temporary Staffing / Employment Services", label:"Temporary Staffing / Employment Services" },
{ value:"Test & Measurement Equipment", label:"Test & Measurement Equipment" },
{ value:"Textile Manufacturing", label:"Textile Manufacturing" },
{ value:"Think Tanks", label:"Think Tanks" },
{ value:"Ticket Sales", label:"Ticket Sales" },
{ value:"Tires & Rubber", label:"Tires & Rubber" },
{ value:"Tobacco Manufacturing", label:"Tobacco Manufacturing" },
{ value:"Toys & Games, Manufacturing", label:"Toys & Games, Manufacturing" },
{ value:"Toys & Games, Retail", label:"Toys & Games, Retail" },
{ value:"Training", label:"Training" },
{ value:"Translation & Linguistic Services", label:"Translation & Linguistic Services" },
{ value:"Translation and Localization", label:"Translation and Localization" },
{ value:"Transportation", label:"Transportation" },
{ value:"Transportation Equipment Manufacturing", label:"Transportation Equipment Manufacturing" },
{ value:"Transportation, Logistics, Supply Chain and Storage", label:"Transportation, Logistics, Supply Chain and Storage" },
{ value:"Travel Arrangements", label:"Travel Arrangements" },
{ value:"Tribal Nations", label:"Tribal Nations" },
{ value:"Trucking", label:"Trucking" },
{ value:"Venture Capital & Private Equity", label:"Venture Capital & Private Equity" },
{ value:"Venture Capital and Private Equity Principals", label:"Venture Capital and Private Equity Principals" },
{ value:"Veterinary Services", label:"Veterinary Services" },
{ value:"Warehousing and Storage", label:"Warehousing and Storage" },
{ value:"Watches & Jewelry, Manufacturing", label:"Watches & Jewelry, Manufacturing" },
{ value:"Wellness and Fitness Services", label:"Wellness and Fitness Services" },
{ value:"Wholesale", label:"Wholesale" },
{ value:"Wineries", label:"Wineries" },
{ value:"Wire & Cable,", label:"Wire & Cable," },
{ value:"Writing and Editing", label:"Writing and Editing" },
{ value:"Zoos & National Parks", label:"Zoos & National Parks" }
    ],
  },
  {
    id: "level",
    name: "Job Level",
    options: [
      // Cities could be dynamically loaded based on the selected state
      { value: "Manager", label: "Manager" },
      {
        value: "Board Memebers and Owners",
        label: "Board Memebers and Owners",
      },
      { value: "Individual Contributor", label: "Individual Contributor" },
      { value: "Vice President", label: "Vice President" },
      { value: "Director", label: "Director" },
      { value: "C-Level", label: "C-Level" },
      // { value: "Supervisor", label: "Supervisor" },
    ],
  },
  {
    id: "function",
    name: "Job Function",
    options: [
      // Cities could be dynamically loaded based on the selected state
      { value: "Customer Service", label: "Customer Service" },
      { value: "Education", label: "Education" },
      { value: "Engineering", label: "Engineering" },
      { value: "Finance", label: "Finance" },
      { value: "Government", label: "Government" },
      { value: "Healthcare Services", label: "Healthcare Services" },
      { value: "Human Resources", label: "Human Resources" },
      { value: "IT", label: "IT" },
      { value: "Legal", label: "Legal" },
      { value: "Marketing", label: "Marketing" },
      { value: "Operations", label: "Operations" },
      { value: "Other", label: "Other" },
      { value: "Sales", label: "Sales" },

      // Add more cities as needed
    ],
  },
];

export default filters;
